// This file is auto-generated by TanStack Router
import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CreateImport } from './routes/create'
import { Route as EditImport } from './routes/edit'

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const EditRoute = EditImport.update({
  path: '/edit',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByPath {
  '/': { preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
  '/create': { preLoaderRoute: typeof CreateImport; parentRoute: typeof rootRoute }
  '/edit': { preLoaderRoute: typeof EditImport; parentRoute: typeof rootRoute }
}

export const routeTree = rootRoute.addChildren([IndexRoute, CreateRoute, EditRoute])
